spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=blog_user
spring.datasource.password=asadik

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=8080

# JWT 
jwt.secret=ca8XENrYTQ1x+h6iq9MHoisLtNBNsF4tzPbsnEP+Cg4=
jwt.expiration=86400000